{{- if .Values.account.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.account.name }}
  labels:
    {{- include "currency.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
{{- end }}
