services:
  postgres:
    container_name: muffin-postgres
    image: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=muffin-wallet
      - POSTGRES_PASSWORD=muffin-wallet
      - POSTGRES_DB=muffin_wallet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
  loki:
    image: grafana/loki:latest
    container_name: loki
    network_mode: host
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    ports:
      - "3000:3000"
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin:2.24.3
    container_name: zipkin
    ports:
      - "9411:9411"
    network_mode: host
    restart: unless-stopped

volumes:
  db_data:
